name: Update the repository with the latest base16 colorschemes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@v3
      - name: Update schemes
        uses: base16-project/base16-builder-go@latest
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update with the latest colorschemes
          branch: ${{ github.head_ref }}
